openapi: 3.0.1
info:
  title: Upload Events
  version: 0.0.1
servers:
  - url: /api
paths:
  /upload:
    post:
      summary: Upload Events
      operationId: postEvents  # The function name (in clients and servers)
      x-jvm-package: events    # Convention for generated classes: In this case `EventsClient, EventsResource`
      requestBody:
        description: List of Events
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Event'
        required: true
      responses:
        200:
          description: OK
          content: { }
        400:
          description: Bad request, payload has wrong format
          content: { }
components:
  schemas:
    Event:
      type: object
      properties:
        unit_id:
          type: string
        user_age:
          type: integer
        user_date:
          type: string
          format: date