name: CI
on:
  push:
    branches:
      - master
      - migrate_pekko
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # https://github.com/coursier/setup-action
      - name: Set up JDK 17
        uses: coursier/setup-action@v3
        with:
          jvm: 17
          apps: sbtn
      - name: Build and Test
        run: sbt -v +test